### ISSUE TITLE
Dockerfile for Quarkus native examples

### ISSUE THREAD

**Issue by SandraAhlgrimm** [Azure-Samples/java-native-telemetry#18]
I need a single Dockerfile at root level for the container deployment.

Please ensure to use multi stage containers and include the build in the Dockerfile.

**Comment by brunobat** [comment]
@SandraAhlgrimm please check if these dockerfiles work for you: https://github.com/Azure-Samples/java-native-telemetry/blob/ee6d4e5f818f02fcee84e21d58933f0aab7dc76c/code/quarkus-telemetry/quarkus-telemetry-vegetable/src/main/docker

**Comment by SandraAhlgrimm** [comment]
"I need a single Dockerfile at root level for the container deployment.
Please ensure to use multi-stage containers and include the build in the Dockerfile."

That would be the easiest and most consistent way.

**Comment by SandraAhlgrimm** [comment]
"I need a single Dockerfile at root level for the container deployment.
Please ensure to use multi-stage containers and include the build in the Dockerfile."

That would be the easiest and most consistent way.
